### ISSUE TITLE
网络错误

### ISSUE THREAD

**Issue by XKangs** [Hermit10/temp#1]
我正确设置好代理后运行网络检测会出现错误
代理模式为HTTP时
`[-]Connect retry 1/3
Error in get_html :HTTPSConnectionPool(host='avsox.website', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
[-]Connect retry 2/3
Error in get_html :HTTPSConnectionPool(host='avsox.website', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
Error in get_html :HTTPSConnectionPool(host='xcity.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
[-]Connect retry 1/3
Error in get_html :HTTPSConnectionPool(host='xcity.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
[-]Connect retry 2/3
Error in get_html :HTTPSConnectionPool(host='xcity.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
Error in get_html :HTTPSConnectionPool(host='www.mgstage.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
[-]Connect retry 1/3
Error in get_html :HTTPSConnectionPool(host='www.mgstage.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
[-]Connect retry 2/3
Error in get_html :HTTPSConnectionPool(host='www.mgstage.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!`

当代理模式为socks5时
`Error in get_html :SOCKSHTTPSConnectionPool(host='www.javbus.com', port=443): Read timed out. (read timeout=7)`

我之前怀疑是我代理有问题，可是我Chrome用的是同一个代理，却也能正常访问上述网站
所以我怀疑是不是Python依赖的版本有问题，导致Python和我的代理有兼容性问题

**Comment by Hermit10** [comment]
好像是有问题。😓我一直用路由器科学上网，没发现，等抽空看看能不能改。。

**Comment by Hermit10** [comment]
pip install pysocks

安装这个模块后，socks5正常了。原因是Python 本身在没有安装 pysocks 时并不支持 socks5 代理。
问题参考：https://blog.csdn.net/whatday/article/details/109287343

![image](https://user-images.githubusercontent.com/24836174/120845491-7cdafe80-c5a3-11eb-9ea2-dc8b58815374.png)

![image](https://user-images.githubusercontent.com/24836174/120845536-8f553800-c5a3-11eb-9598-0df9ff8fa848.png)

**Comment by XKangs** [comment]
> pip install pysocks
> 
> 安装这个模块后，socks5正常了。原因是Python 本身在没有安装 pysocks 时并不支持 socks5 代理。
> 问题参考：https://blog.csdn.net/whatday/article/details/109287343
> 
> ![image](https://user-images.githubusercontent.com/24836174/120845491-7cdafe80-c5a3-11eb-9ea2-dc8b58815374.png)
> 
> ![image](https://user-images.githubusercontent.com/24836174/120845536-8f553800-c5a3-11eb-9598-0df9ff8fa848.png)

我之前已经装过pysocks了，但旧的版本依然无法正常使用socks5的代理
今天更新的这个新版本设置socks5代理后可以使用了，但javbus，javdb和jav321都无法连接，也无法正常刮削。
网络检测
```
 检测网络中，请等待...
   github  ✅ 连接正常
   javbus  ❌ https://www.javbus.com 连接失败，请检查网络或代理设置！
   javdb   ❌ https://www.javdb.com 连接失败，请检查网络或代理设置！
   jav321  ❌ https://www.jav321.com 连接失败，请检查网络或代理设置！
   dmm     ✅ 连接正常
   avsox   ✅ 连接正常
   xcity   ✅ 连接正常
   mgstage ✅ 连接正常
```
但同样的代理设置我用浏览器是可以正常打开这些网站的
所以我怀疑是不是那三个网站设置了某种http header可以自动识别爬虫并拒绝访问呢

**Comment by XKangs** [comment]
今天更新的版本我依然无法使用http代理

![image](https://user-images.githubusercontent.com/17783163/120892508-45229400-c641-11eb-9195-4d326f45595d.png)

**Comment by XKangs** [comment]
另外我还发现新版本无法保存设置
具体表现为我在设置中修改了代理相关的设置后，点击下方的保存
然后关闭软件重新打开，设置依然是原来的

只能手动编辑config.ini修改

**Comment by Hermit10** [comment]
试了下，win版好像不能保存配置，py版可以保存。待研究下原因。
socks5问题，我也遇到了，今天把pysocks卸载重装了下，就一直连不了了。
幸好http可改好了，先用着http吧。

**Comment by XKangs** [comment]
> 试了下，win版好像不能保存配置，py版可以保存。待研究原因。
> socks5问题，我也遇到了，今天把pysocks卸载重装了下，就一直连不了了。
> 幸好http改好了，先用着http吧。😀

我用的就是py版本，但也无法保存配置。
我怀疑和Python的版本有关系
毕竟exe的版本也是py版本打包的，可能依赖那些有问题

我测试完http后切换回socks5，发现socks5又用不了了

**Comment by Hermit10** [comment]
有可能，刚刚我把python版本换成3.9.0，socks5又好了。。😄

**Comment by XKangs** [comment]
> 有可能，刚刚我把python版本换成3.9.0，socks5又好了。。😄

我用的就是Python 3.9.4  win64，但socks5之前可以后来又不行。真的好玄学
我一度怀疑我的代理软件有问题，昨晚把clash for linux更新到了最新的1.60，发现也还是不行

**Comment by XKangs** [comment]
3.963-20210606版本的HTTP代理已经正常了
但是socks5还是不正常，而且还是无法保存配置文件

**Comment by XKangs** [comment]
以及版本更新检测现在检测的是原作者moyy996的版本

**Comment by Hermit10** [comment]
已加上更新检测。0608版本已发。

![image](https://user-images.githubusercontent.com/24836174/121089009-1b23ca00-c819-11eb-98a3-72a883265a17.png)
