### ISSUE TITLE
所有刮削结果的tag里都会出现一个""多選提交""的标签

### ISSUE THREAD

**Issue by haobula** [Hermit10/temp#10]

**Comment by Hermit10** [comment]
截图看下

**Comment by Hermit10** [comment]
试了下，简体繁体日语都复现不了，最好上图看看啥问题。

**Comment by haobula** [comment]
網站選擇javbus,就會出現多選提交的問題.

![screenshot12](https://user-images.githubusercontent.com/84738840/123898697-5dfc3c00-d998-11eb-914b-9678e38a5d75.png)
![screenshot13](https://user-images.githubusercontent.com/84738840/123898701-5f2d6900-d998-11eb-9016-a2b486fe7de2.png)
![screenshot14](https://user-images.githubusercontent.com/84738840/123898702-5fc5ff80-d998-11eb-9b4f-173198f0002b.png)
![screenshot15](https://user-images.githubusercontent.com/84738840/123898705-5fc5ff80-d998-11eb-95f6-3b7999ff6748.png)

**Comment by Hermit10** [comment]
👌，后面处理下

**Comment by Hermit10** [comment]
已修复，更新0702版本。
