### ISSUE TITLE
能否增加是否翻译的选项，谢谢

### ISSUE THREAD

**Issue by xlsword78** [Hermit10/temp#11]

**Comment by Hermit10** [comment]
选择日语就是不翻译

**Comment by xlsword78** [comment]
在https://jp.airav.wiki/刮削影片，显示日志如下
![jp airav wiki](https://user-images.githubusercontent.com/77871090/123922054-39b15700-d9ba-11eb-9d62-01a29b991778.jpg)
日志中显示详情页为https://jp.airav.wiki/video/caribbeancom122919-001，此网页为日语网页，如下
![jp airav wiki详情页](https://user-images.githubusercontent.com/77871090/123922317-7da45c00-d9ba-11eb-99a9-7d31b79b097b.jpg)
但刮削出来的都是繁体中文显示，我的软件设置翻译选的就是日语
![设置](https://user-images.githubusercontent.com/77871090/123922542-b8a68f80-d9ba-11eb-8d0a-d4faf7a1f96e.jpg)

**Comment by Hermit10** [comment]
好，我看看问题

**Comment by xlsword78** [comment]
另外在avsox网站刮削是，刮削到的标题前后总是多(' 与',)这两个符号
![0](https://user-images.githubusercontent.com/77871090/123971092-52d2fb80-d9ec-11eb-9860-1dafc0ef6123.jpg)

**Comment by Hermit10** [comment]
翻译的问题，原因是这个页面返回的语言是不固定的，和代理节点有关，不同节点语言是变化的。。。
avsox问题我看看

**Comment by Hermit10** [comment]
已修复，更新0702版本。
