### ISSUE TITLE
翻译有问题

### ISSUE THREAD

**Issue by haobula** [Hermit10/temp#14]
不知道为什么,现在刮削后翻译的结果完全是乱来的,3号之前是正常的从4号开始完全就是随心所欲的状态了.

偶尔标题也是乱的

![screenshot16](https://user-images.githubusercontent.com/84738840/124768792-8c1ae680-df6b-11eb-8a60-f94924f28c0d.png)

**Comment by Hermit10** [comment]
好，我看下。

**Comment by Hermit10** [comment]
已修复。更新版本20210708
