### ISSUE TITLE
javdb刮削报错

### ISSUE THREAD

**Issue by prettyboyzhuo** [Hermit10/temp#16]
>>> JAVDB-开始使用 javdb 进行刮削
   >>> JAVDB-生成搜索页地址: https://javdb.com/search?q=MMGH-278&f=all&locale=zh
   >>> JAVDB-请求搜索页：出错！错误信息：HTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=MMGH-278&f=all&locale=zh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BD032ECCA0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[!] 🔴 Error: JAVDB-请求搜索页：出错！错误信息：HTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=MMGH-278&f=all&locale=zh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BD032ECCA0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by Hermit10** [comment]
更新版本20210711试试

**Comment by Hermit10** [comment]
如果还有问题，可试试这个方法：
https://www.shuzhiduo.com/A/1O5EOg8rz7/
