### ISSUE TITLE
jav321刮削出错

### ISSUE THREAD

**Issue by BCYDTZ** [Hermit10/temp#17]
[+] 🙈 Requesting Data for [Z://1/300MAAN-374.mp4], the number is [300MAAN-374]
[!] 🙉 Data request successfully!
[+] ****** Debug Info* *****
   >>> MGSTAGE-开始使用 mgstage 进行刮削
   >>> JAV321-开始使用 jav321 进行刮削
   >>> JAV321-数据获取成功！
   >>> 提示：有道翻译接口请求失败，将跳过翻译！错误：HTTPConnectionPool(host='dog.youdao.com', port=80): Read timed out. (read timeout=5)
   >>> title        : 颜◎乳◎クビレ◎尻◎感度◎缔まり◎！SSRなエロ女神をクラブで见つけて即ナンパ→ワンナイトSEX！お酒弱いのにテキーラ连饮みでへべれけ！感度上がりすぎてパン染みべっとり！超ご奉仕型のフェラテク最高！オイルまみれの柔スベ肌が超気持ち良いんだが！激烈に缔まる吸着究极マ○コは入れただけで天国确定！ワンナイトだけじゃもったいない、存在がエロすぎる女神“れーちゃむ”はセフレにしたい女No.1のエロ女神だった！！
   >>> number       : MAAN-374
   >>> actor        : れーちゃむ
   >>> tag          : ナンパ, パイパン, 巨乳
   >>> release      : 2019-03-18
   >>> year         : 2019
   >>> runtime      : 68
   >>> score        : 4.7
   >>> studio       : プレステージプレミアム(PRESTIGE PREMIUM)
   >>> publisher    : プレステージプレミアム(PRESTIGE PREMIUM)
   >>> source       : jav321.main
   >>> website      : https://www.jav321.com/video/300maan-374
   >>> cover        : https://www.jav321.com/images/prestigepremium/300maan/374/pb_e_300maan-374.jpg
   >>> cover_small  : https://www.jav321.com/images/prestigepremium/300maan/374/pf_o1_300maan-374.jpg
[+] 🟢 Folder created successfully!
[+] 🟢 Thumb downloaded successfully!
[!] 🔴 Error: getJsonData error : local variable 'ex' referenced before assignment

**Comment by Hermit10** [comment]
更新版本20210711

**Comment by BCYDTZ** [comment]
> 更新版本20210711

已更新，可以了
