### ISSUE TITLE
能否细化对有中文字幕视频的重命名细化功能

### ISSUE THREAD

**Issue by happywilly** [Hermit10/temp#18]
现在系统会自动把 -C 结尾的 电影打标成中文字幕 并重命名为-C
但是现在很多中文字幕电影的结尾是不一样的 有的-ch  有的 -R 有的 -c
所以希望能够自定义这个识别

或者有另外一个实现方法 就是提供一个 取消 自动识别中文字幕的功能   我自己做一个命名规则，把我某个文件夹里的所有文件都加中文字幕的-C后缀   因为现在不支持取消  所以 会出现  -C-C的情况

感谢

**Comment by Hermit10** [comment]
自定义中文字幕特征是可以的，或者如果你可以提供一些例子，我可以做内置

-C-C这种不应该出现，因为最终的文件名字是用识别出的番号和-C相加的，番号本身不会有-C
如果出现-C-C，估计是一个bug，可以截图看看

**Comment by happywilly** [comment]
嗯嗯  现在的中文字幕资源主要是  stars-372c.mp4  stars-372-C.mp4  stars-372ch.mp4 stars-372R.mp4  这几种类型 另外hjd的很多中文字幕没有后缀，但是依然有中文字幕，所以就比较麻烦。

我说的-C-C坦白说没试过  因为我自己的命名规则  stars-372R  所以有些重命名会出现 stars-372R-C的情况  不过如果你说最终不会出现-C-C的话  那是不是意味着我可以把命名规则 naming_file = [FHD]number-C 这样就可以曲线实现功能

**Comment by Hermit10** [comment]
是的。

**Comment by Hermit10** [comment]
已修改。更新20210803版本。
