### ISSUE TITLE
最新版本刮削无反应

### ISSUE THREAD

**Issue by xlsword78** [Hermit10/temp#19]
选择文件开始刮削后无任何反应，确认本地网络无问题，可访问所有影片元数据网站。
Create log file: D:\AVDCx\Log\2021-07-14-13-47-45.txt

AVDCx 20210714
基于项目 https://github.com/moyy996/AVDC 修改
报告问题 https://github.com/Hermit10/temp/issues

================================================================================
                               Update Checking...                               
                          No Newer Version Available!                           
================================================================================
 📺 Find 1 movies

1/1 (100.00%) round(1)
================================================================================
 📺 Find 1 movies

1/1 (100.00%) round(2)
================================================================================

**Comment by Hermit10** [comment]
config.ini发一下
这个文件夹里视频文件的完整路径和名字是怎样的？

**Comment by xlsword78** [comment]
[2021-07-14-13-30-29.txt](https://github.com/Hermit10/temp/files/6814645/2021-07-14-13-30-29.txt)
[2021-07-14-13-40-19.txt](https://github.com/Hermit10/temp/files/6814646/2021-07-14-13-40-19.txt)
[2021-07-14-13-47-45.txt](https://github.com/Hermit10/temp/files/6814647/2021-07-14-13-47-45.txt)
以上是下载了新版本后进行的三次刮削。
视频文件路径纯英文：E:\abc\def，文件名称纯数字番号：123456-001。本次版本之前都是在此文件路径和命名方式下进行的

**Comment by Hermit10** [comment]
好，我看看

**Comment by BCYDTZ** [comment]
> 好，我看看

目前是单个刮削出错

**Comment by Hermit10** [comment]
已修改，更新20210715版本试试。
