### ISSUE TITLE
网络代理无效

### ISSUE THREAD

**Issue by kofzhanganguo** [Hermit10/temp#2]
![image](https://user-images.githubusercontent.com/32073931/120889955-6465f500-c632-11eb-9268-5e42e71c07b1.png)
![image](https://user-images.githubusercontent.com/32073931/120889971-83fd1d80-c632-11eb-97a8-3ef73528195c.png)
![image](https://user-images.githubusercontent.com/32073931/120889983-911a0c80-c632-11eb-8f3b-2c087edbf908.png)
求解决办法。

**Comment by XKangs** [comment]
同样的问题
我之前已经开过一个issue了

**Comment by kofzhanganguo** [comment]
不知道咋解决这个问题，现在只能用EMBY的插件刮削了，对付用一下，期待作者修复一下网络代理的BUG。

**Comment by Hermit10** [comment]
下载0606版本，已解决这个问题。

**Comment by kofzhanganguo** [comment]
代理问题解决了，感谢作者。

**Comment by Hermit10** [comment]
fixed
