### ISSUE TITLE
javbus和mgstage问题

### ISSUE THREAD

**Issue by 18E42D38dFA2** [Hermit10/temp#20]
![Screenshot 2021-07-14 101153](https://user-images.githubusercontent.com/87431855/125637064-a9d1798c-187a-4cd4-bc1e-cfe925b6962f.jpg)
![Screenshot 2021-07-14 101507](https://user-images.githubusercontent.com/87431855/125637536-39ecec57-cde3-426a-940c-fcccd2c5783a.jpg)
javbus有个别能刮成功，但是下不了剧照，mgstage就完全用不了

**Comment by Hermit10** [comment]
mgstage网站挂了吧，你浏览器打开看看
javbus是连接超时，换个代理或者把超时时间弄久一些。
![image](https://user-images.githubusercontent.com/24836174/125645933-515fcc08-98bb-4953-9fa5-b3926bea62b4.png)

**Comment by 18E42D38dFA2** [comment]
![1](https://user-images.githubusercontent.com/87431855/125670688-e6d708dd-5373-41bf-b91d-ec621eb91013.jpg)
![2](https://user-images.githubusercontent.com/87431855/125670697-9165e3dc-fce2-46eb-955a-157468f35d0d.jpg)
![3](https://user-images.githubusercontent.com/87431855/125670706-91a2a2cd-b7e4-4fdf-a81b-5cc40779d33c.jpg)
你演示的是PY版，我用的是WIN，不知道你有没有测试过。
旧版是没这问题的，用了0715的版本也是这样，图1左边为新版。
mgstage我开着来刮也是不行，图2是新，3是旧版

**Comment by Hermit10** [comment]
![image](https://user-images.githubusercontent.com/24836174/125705410-2eab84b3-511b-49f7-a400-85d59a423599.png)
![image](https://user-images.githubusercontent.com/24836174/125705546-8f89daac-c541-4c3a-b0ec-19ee1614963d.png)

**Comment by Hermit10** [comment]
又修改了下，你重新下载20210715试试（版本号没改，包替换了。）
javbus是因为下载时没有走代理，mgstage是获取评分时有一个报错

**Comment by 18E42D38dFA2** [comment]
测试了一下功能都正常了，要是mgstage能用高清封面就更好了，比如现在默认刮的是 https://image.mgstage.com/images/reiwashirouto/383reiw/083/pb_p_383reiw-083.jpg，高清源为https://image.mgstage.com/images/reiwashirouto/383reiw/083/pb_e_383reiw-083.jpg，就一个字母的区别而已。
另外有没有考试过增加FC2的官方源？第三方源太乱了用不惯

**Comment by Hermit10** [comment]
官方源指哪个？

**Comment by 18E42D38dFA2** [comment]
https://adult.contents.fc2.com/

**Comment by Hermit10** [comment]
封面已修改，更新20210716版本。

**Comment by 18E42D38dFA2** [comment]
> 封面已修改，更新20210716版本。
![2](https://user-images.githubusercontent.com/87431855/125971549-b5b21a97-b4bd-4550-bc3d-54c1afce9fcb.jpg)
忘了一个问题，mgs封面有两个版本的，现在直接从thumb剪的话会出现人物对不上的情况，能不能分开获取呢？
poster应该是pf_e_番号，thumb才是pb_e_番号,

**Comment by Hermit10** [comment]
设置里poster选择下载即可，不然就是裁剪。

**Comment by 18E42D38dFA2** [comment]
> 设置里poster选择下载即可，不然就是裁剪。

![1](https://user-images.githubusercontent.com/87431855/125980995-cc53d875-cb02-48e3-ba25-9c8a1dff1a6a.jpg)
试了不行，最终还是变成裁剪,而且看图片地址还是低清的

**Comment by Hermit10** [comment]
已修改，请更新20210718版本。
