### ISSUE TITLE
最新AVDCx-win-20210716 版本 WIN7 64位运行出错

### ISSUE THREAD

**Issue by ljjwy168** [Hermit10/temp#22]
提示丢失API-ms-win-core-path-1-1-1.dll
还有提示
error loading python dll
python39.dll
找不到指定模块

**Comment by Hermit10** [comment]
改天我用虚拟机看看

**Comment by ljjwy168** [comment]
> 改天我用虚拟机看看

你好 还有个问题想问下 我以前是用AVDC刮削的 视频文件夹名都是英文的 用了AVDCX后 文件夹名可以是中文 挺好的 
我以前用AVDX刮削的日文文件夹名想弄成中文的是必须要重新刮削吗 还是有其他办法

**Comment by Hermit10** [comment]
必须重新刮削

**Comment by ljjwy168** [comment]
> 改天我用虚拟机看看

您好 请问确定WIN7不能使用是系统问题还是软件问题了吗

**Comment by Hermit10** [comment]
还没看，这个一般是win7系统缺少一些插件，解决办法是把插件内置到程序里或自行下载安装相关缺少插件

**Comment by ljjwy168** [comment]
> 还没看，这个一般是win7系统缺少一些插件，解决办法是把插件内置到程序里或自行下载安装相关缺少插件

不行 差的文件太多 换系统了只能

**Comment by Hermit10** [comment]
已适配win7 64位，更新版本20210727
