### ISSUE TITLE
FC2官方源问题

### ISSUE THREAD

**Issue by 18E42D38dFA2** [Hermit10/temp#24]
![1](https://user-images.githubusercontent.com/87431855/126315948-f063c7c8-e83b-4376-ade3-42bc046b8b65.jpg)
如图所示，刮的时候显示无码，最终生成的nfo变成有码，用fc2hub没这问题
![2](https://user-images.githubusercontent.com/87431855/126316074-8844d1ff-a03a-440f-b67f-1ff7a9f367e1.jpg)
还有就是能不能把卖家直接刮成演员？我看了命令行版的逻辑都是这样，现在全成FC2系列一下分不出是谁。

最后就是现在自带的源已经很多了，能不能自行调整优先级或者只选用其中几个源来刮？

**Comment by Hermit10** [comment]
好。我看看。
如果支持调整，你会怎么调整？

**Comment by Hermit10** [comment]
![CD1BF1FC-1DF7-420E-8447-F7463F217195](https://user-images.githubusercontent.com/24836174/126323035-793d66d0-7ffa-4883-9c19-3d9f5e5a3369.png)

目前卖家信息是作为厂商显示的。

**Comment by 18E42D38dFA2** [comment]
> ![CD1BF1FC-1DF7-420E-8447-F7463F217195](https://user-images.githubusercontent.com/24836174/126323035-793d66d0-7ffa-4883-9c19-3d9f5e5a3369.png)
> 
> 目前卖家信息是作为厂商显示的。

隔壁有把卖家加到厂商，不过也加到演员里了

**Comment by 18E42D38dFA2** [comment]
> 好。我看看。
> 如果支持调整，你会怎么调整？

我的建议就是给源加个序号，把想用的手动排到123，前面的源搜不到再调用其他源

**Comment by Hermit10** [comment]
个人感觉没必要。现在fc2的查询顺序是fc2-fc2club-fc2hub，不是按照列表里的顺序。

**Comment by 18E42D38dFA2** [comment]
> 个人感觉没必要。现在fc2的查询顺序是fc2-fc2club-fc2hub，不是按照列表里的顺序。

不是只针对fc2，比如我一般用javbus做首要源，用现在的排序我就得单选来刮，还有mgstage有时会跳到jav321，这两个站的番号规则不一样，经常把我的番号删了几位，所以我觉得出个选择和排序功能还是有必要的

**Comment by Hermit10** [comment]
如果是其他番号，目前不好改。现在是不同番号有不同的顺序。需要增加很多设置，

**Comment by 18E42D38dFA2** [comment]
那现阶段就只能分开来刮了，先处理FC2那两个问题吧

**Comment by 18E42D38dFA2** [comment]
突然想到个问题，因为我的nfo是番号+标题+演员，碰到未知演员的话能不能在nfo里也写出来，比如
<title>CLUB-644 ホテルの予約ミスで相部屋になった女上司とチェックアウトまでめちゃくちゃ中出し交尾した一部始終 未知演员<title>
  <actor>
    <name>未知演员</name>
  <actor>

**Comment by 18E42D38dFA2** [comment]
突然想到个问题，因为我的nfo是番号+标题+演员，碰到未知演员的话能不能在nfo里也写出来，比如
![1](https://user-images.githubusercontent.com/87431855/126336401-d4b22268-cb3b-4f5d-81d5-e11dadc12b94.jpg)

**Comment by 18E42D38dFA2** [comment]
![2](https://user-images.githubusercontent.com/87431855/126338809-91a88400-ee6d-4b20-906d-29fa56b69873.jpg)
看了下隔壁的wiki，他们是可以调整的，不知道这边的逻辑是不是和他们一样

**Comment by Hermit10** [comment]
> 突然想到个问题，因为我的nfo是番号+标题+演员，碰到未知演员的话能不能在nfo里也写出来，比如
> ![1](https://user-images.githubusercontent.com/87431855/126336401-d4b22268-cb3b-4f5d-81d5-e11dadc12b94.jpg)

未知演员写到nfo好像没啥意义吧？有需求场景？

**Comment by 18E42D38dFA2** [comment]
> > 突然想到个问题，因为我的nfo是番号+标题+演员，碰到未知演员的话能不能在nfo里也写出来，比如
> > ![1](https://user-images.githubusercontent.com/87431855/126336401-d4b22268-cb3b-4f5d-81d5-e11dadc12b94.jpg)
> 
> 未知演员写到nfo好像没啥意义吧？有需求场景？

我的话可以在后期筛选出来然后补名字，现在没写的话有点难找，其他人有没有这需求我就不知道了

**Comment by Hermit10** [comment]
未知演员后面再改吧，fc2的已修改，更新20210721版本。

**Comment by Hermit10** [comment]
> > > 突然想到个问题，因为我的nfo是番号+标题+演员，碰到未知演员的话能不能在nfo里也写出来，比如
> > > ![1](https://user-images.githubusercontent.com/87431855/126336401-d4b22268-cb3b-4f5d-81d5-e11dadc12b94.jpg)
> > 
> > 
> > 未知演员写到nfo好像没啥意义吧？有需求场景？
> 
> 我的话可以在后期筛选出来然后补名字，现在没写的话有点难找，其他人有没有这需求我就不知道了

未知演员已更新，版本20210725
