### ISSUE TITLE
关于翻译问题,可以增加一个翻译选择问题吗?

### ISSUE THREAD

**Issue by saz369** [Hermit10/temp#25]
因为如果翻译了文件名,到后期想查找类似片子的时候,因为日文和中文的分别导致找不到. 希望能够增加一个选项,只翻译翻译简介.谢谢.ps:接受赞助吗?

**Comment by Hermit10** [comment]
可以。不用赞助，谢谢。

**Comment by Hermit10** [comment]
已添加，更新版本20210725.
