### ISSUE TITLE
关于未知演员命名的自定义规则

### ISSUE THREAD

**Issue by kofzhanganguo** [Hermit10/temp#27]
![image](https://user-images.githubusercontent.com/32073931/126413958-f5da39c6-2f1d-4667-b9bb-8d4ee42b9e4c.png)
这里应该添加一下自定义命名规则，并不是素人，有的片子是没有演员名单，比如SW系列等或者是少数片商不给演员名单，装成素人，其实都AV女优，这里应该添加一下自定义命名名称，比如Unknown，或者是未知演员等等。
![image](https://user-images.githubusercontent.com/32073931/126414228-68f81ad7-9c72-4b19-bb0c-afc0b657b82d.png)
这样显示文件夹，容易让人误导，还以为是素人片商发布的片子呢。

**Comment by Hermit10** [comment]
这个素人估计是网站演员信息给的，你看看是哪个网站？

**Comment by kofzhanganguo** [comment]
这个我还真不清楚是啥网站，一会儿等我下载完片子，刮削一下试试看，主要是这个容易让人误导，本身不是素人的番号片子，刮削出来的片名带素人，这样很麻烦，应该可以自定修改一下这个未知演员的名称，让用户自己定义改名一下，这样才科学。

**Comment by Hermit10** [comment]
这和未知演员是两回事。
当没有演员信息时，演员名称只会写成「未知演员」，不会写成「素人」。
这个素人是网站信息不对造成的。
