### ISSUE TITLE
0729版封面剧照问题

### ISSUE THREAD

**Issue by 18E42D38dFA2** [Hermit10/temp#29]
![1](https://user-images.githubusercontent.com/87431855/127474468-6e49e16a-3aa5-4c93-b97c-b52ec88aaae2.jpg)
![3](https://user-images.githubusercontent.com/87431855/127474587-1ff157dd-4ca0-49a3-9c5a-331d4ccd8be7.jpg)
封面裁剪有问题,剧照也没下成功,上一版本没事
![4](https://user-images.githubusercontent.com/87431855/127474675-495e2fef-5ed9-4d76-b3c8-91a03e30f417.jpg)
还有这个无码到底是怎么判定的?明显错了

**Comment by Hermit10** [comment]
无码是根据页面返回的当前选中的tab来判断的。
当是无码时，裁剪会使用中间裁剪。

**Comment by 18E42D38dFA2** [comment]
那就是mosaic出问题了，我刮了5部片全错了，剧照也下不了，全是1K的图

**Comment by Hermit10** [comment]
已修复，更新20210730版本试试。
