### ISSUE TITLE
建议移除javlibrary吧

### ISSUE THREAD

**Issue by tanlicheng703283** [Hermit10/temp#30]
因为一旦某番号已经发行超过百位数时搜寻就会有问题
例如 IPX-XXX 目前已经到 IPX-715 
只要搜寻 IPX-071 就会 出现 IPX-071  IPX-710 IPX-711,IPX-712,IPX-713,IPX-714,715
如果搜寻 IPX-007 就会出现 IPX-007 IPX-（070-079）  IPX-711,IPX-712,IPX-713,IPX-714,715
 AVDVX的讯息
 🙈 [Movie] D:\AV_Data_Capture\AVDCX-TEST\failed\SNIS-003.mp4
 🚘 [Number] SNIS-003
 🌐 [website] javlibrary[jp]
 🟠 Data failed!
   ****** Debug Info ******
   >>> javlibrary-开始使用javlibrary 进行刮削
   >>> javlibrary-生成搜索页地址: http://www.javlibrary.com/ja/vl_searchbyid.php?keyword=SNIS-003
   >>> javlibrary-搜索结果页：未匹配到番号！
 🔴 [Error] javlibrary-搜索结果页：未匹配到番号

**Comment by Hermit10** [comment]
好，我看看

**Comment by Hermit10** [comment]
已修改。更新20210803版本。

**Comment by tanlicheng703283** [comment]
20210803版 的新問題
  <tag>單</tag>
  <tag>體</tag>
  <tag>作</tag>
  <tag>品</tag>
  <tag>,</tag>
  <tag>巨</tag>
  <tag>乳</tag>
  <tag>,</tag>
  <tag>首</tag>
  <tag>次</tag>
  <tag>亮</tag>
  <tag>相</tag>
  <tag>,</tag>
  <tag>藍</tag>
  <tag>光</tag>
  <tag>,</tag>
  <tag>藝</tag>
  <tag>人</tag>
  <tag>,</tag>
  <tag>薄</tag>
  <tag>馬</tag>
  <tag>賽</tag>
  <tag>克</tag>

**Comment by tanlicheng703283** [comment]
"<tag>單</tag>"

**Comment by tanlicheng703283** [comment]
20210803版的 新问题
标签 被拆开成一个字 例如 "3P" 就变成 3和P 两个标签
         "单体作品" 就变成 单 体 作 品 四个标签
