### ISSUE TITLE
javdb刮削欧美会默认为有码

### ISSUE THREAD

**Issue by xlsword78** [Hermit10/temp#31]
![image](https://user-images.githubusercontent.com/77871090/127760817-0561e2db-57a8-4ee4-bf9e-b5bdccc0466a.png)

**Comment by xlsword78** [comment]
演员名字中间的空格也不见了

**Comment by Hermit10** [comment]
欧美的不是无码吗？要改成欧美？

**Comment by xlsword78** [comment]
7.30版刮削欧美影片的时候会把实际无码的片子标记为有码，刮削出来演员的名字没有空格，影片名称会有丢字的现象，有时会丢最后几个字母，有时会丢首字母，暂时没发现规律

**Comment by xlsword78** [comment]
![屏幕截图 2021-08-01 185219](https://user-images.githubusercontent.com/77871090/127768360-a221f11e-e62a-4890-9d3c-c4480b020d70.jpg)

**Comment by xlsword78** [comment]
title行刮削数据会丢字母，随机丢首字母或者最后几个字母

**Comment by Hermit10** [comment]
已修改。更新20210803版本。

title行丢字母的有例子吗？

**Comment by xlsword78** [comment]
![屏幕截图 2021-08-04 010823](https://user-images.githubusercontent.com/77871090/128058115-51461ed3-3d18-496b-8495-c70f8a58c782.jpg)
![屏幕截图 2021-08-04 011059](https://user-images.githubusercontent.com/77871090/128058134-6685d19f-861b-4326-b941-743d308cee7f.jpg)

**Comment by xlsword78** [comment]
![屏幕截图 2021-08-04 014141](https://user-images.githubusercontent.com/77871090/128061567-cd19ebf6-1fb5-45b2-89cb-d8d1e112beed.jpg)

**Comment by xlsword78** [comment]
8.03版本新问题，tag行在软件日志中显示正常，写入nfo文件为一个字一行，显示在jellyfin媒体库中也如此。
![刮削日志](https://user-images.githubusercontent.com/77871090/128063150-5b3bfcf9-c039-4485-9fcf-491821b5368f.jpg)
![nfo文件](https://user-images.githubusercontent.com/77871090/128063175-3d6a5583-b673-4f96-a795-ef9bcb7811ff.jpg)
![jellyfin](https://user-images.githubusercontent.com/77871090/128063188-54255c80-b88e-46c2-bba9-59ad7e620f21.jpg)

**Comment by Hermit10** [comment]
已更新，20210804版本。
