### ISSUE TITLE
为何变成小写

### ISSUE THREAD

**Issue by tanlicheng703283** [Hermit10/temp#33]
文件夹 以及 文件名 如何设定成大写

**Comment by tanlicheng703283** [comment]
Create log file: D:\AV_Data_Capture\AVDCx\Log\2021-08-04-20-30-02.txt

AVDCx 20210804
 主程序路径：D:\AV_Data_Capture\AVDCx 

基于项目 https://github.com/moyy996/AVDC 修改
报告问题 https://github.com/Hermit10/temp/issues

================================================================================
                               Update Checking...                               
                          No Newer Version Available!                           
================================================================================
 🖥 Movie path: I:/
 📺 Find 1 movies

1/1 (100.00%) round(1) SNIS-041.wmv
================================================================================
 🙈 [Movie] I:\SNIS-041.wmv
 🚘 [Number] snis-041
 ⏱ Please Wait 4 Seconds！
 🌐 [website] javdb
 🟢 Data done!
    title     : 體內汁ダラダラ
    actor     : 吉沢明歩
    tag       : 其他戀物癖,潮吹,薄馬賽克,無碼破解
    release   : 2013-12-07
    year      : 2013
    runtime   : 180
    score     : 4.0
    series    : 体内汁ダラダラ
    director  : 愛染知久
    studio    : S1 NO.1 STYLE
    publisher : S1 NO.1 STYLE
    website   : https://javdb.com/v/Mm6AX
    mosaic    : 有碼
 🟢 Folder done!
 🟢 Thumb done!
 🟢 Poster done!
 🟢 Fanart done!
 🟢 Nfo done!
 ⏳ ExtraFanart downloading...
 🟢 fanart1.jpg done!
 🟢 fanart2.jpg done!
 🟢 fanart3.jpg done!
 🟢 fanart4.jpg done!
 🟢 fanart5.jpg done!
 🟢 fanart6.jpg done!
 🟢 fanart7.jpg done!
 🟢 fanart8.jpg done!
 🟢 fanart9.jpg done!
 🟢 fanart10.jpg done!
 🟢 ExtraFanart downloaded complete! Total 10 , success 10 
 🟢 Movie done! 
 🙉 [Movie] I:\OK\[STUDIO]\[NUMBER]\[snis-041][吉沢明歩]-[體內汁ダラダラ].wmv
================================================================================
 🎉🎉🎉 All finished!!! Total 1 , Success 1 , Failed 0
================================================================================

**Comment by tanlicheng703283** [comment]
🙈 [Movie] I:\SNIS-035.wmv
 🚘 [Number] snis-035
 ⏱ Please Wait 1 Seconds！
 🌐 [website] javdb
 🟢 Data done!
    title     : 犯されたCA
    actor     : ティア
    tag       : 多P,強姦,苗條,薄馬賽克,拘束,無碼破解
    release   : 2013-11-19
    year      : 2013
    runtime   : 150
    score     : 4.42
    series    : 犯されたCA
    director  : 沢庵
    studio    : S1 NO.1 STYLE
    publisher : S1 NO.1 STYLE
    website   : https://javdb.com/v/Rnwn
    mosaic    : 有碼
 🟢 Folder done!
 🟢 Thumb done!
 🟢 Poster done!
 🟢 Fanart done!
 🟢 Thumb add watermark: 字幕!
 🟢 Poster add watermark: 字幕!
 🟢 Nfo done!
 ⏳ ExtraFanart downloading...
 🟢 fanart1.jpg done!
 🟢 fanart2.jpg done!
 🟢 fanart3.jpg done!
 🟢 fanart4.jpg done!
 🟢 fanart5.jpg done!
 🟢 fanart6.jpg done!
 🟢 fanart7.jpg done!
 🟢 fanart8.jpg done!
 🟢 fanart9.jpg done!
 🟢 fanart10.jpg done!
 🟢 ExtraFanart downloaded complete! Total 10 , success 10 
 🟢 Movie done! 
 🙉 [Movie] I:\OK\[S1 NO.1 STYLE]\[snis-035]\[snis-035][ティア]-[犯されたCA].wmv
 🟢 Sub file '[snis-035][ティア]-[犯されたCA].srt' moved successfully!

**Comment by Hermit10** [comment]
已更新，版本2021.08.06。
