### ISSUE TITLE
无法获取封面

### ISSUE THREAD

**Issue by wuyu9** [Hermit10/temp#4]
[从javbus刮削，无法获取封面，信息可以搜索到
![搜狗截图20210606215002](https://user-images.githubusercontent.com/85444707/120926885-5509a900-c711-11eb-8cad-91721b544ea1.png)

**Comment by Hermit10** [comment]
你再试试0608版本，这个问题我没有重现，如果还是会出现，估计要再研究下代码。
![image](https://user-images.githubusercontent.com/24836174/121088123-d8adbd80-c817-11eb-8aa1-59a1748a4724.png)

**Comment by Hermit10** [comment]
已修改，你再试试最新版本
