### ISSUE TITLE
JAVDB依旧不能刮削啊

### ISSUE THREAD

**Issue by CrazyArson** [Hermit10/temp#5]
![QQ截图20210610004104](https://user-images.githubusercontent.com/45677685/121395062-9655bf00-c984-11eb-83b9-9f4c8d9d375f.png)
![QQ截图20210610004141](https://user-images.githubusercontent.com/45677685/121395116-a2da1780-c984-11eb-9819-8f4a3e1d45ee.png)

**Comment by Hermit10** [comment]
可以刮削

![image](https://user-images.githubusercontent.com/24836174/121401285-20088b00-c98b-11eb-856e-78e3267bf342.png)
![image](https://user-images.githubusercontent.com/24836174/121401392-42020d80-c98b-11eb-986f-1a03be29f762.png)

**Comment by Hermit10** [comment]
升级到最新版再试试，如果还不行，把调试模式打开，截图上传下。

**Comment by CrazyArson** [comment]
![image](https://user-images.githubusercontent.com/45677685/121518009-93111080-ca22-11eb-8b15-e12952113afb.png)
![image](https://user-images.githubusercontent.com/45677685/121518036-9b694b80-ca22-11eb-9499-fc2ce74c7444.png)
![image](https://user-images.githubusercontent.com/45677685/121518060-a45a1d00-ca22-11eb-9e74-0590e154d4f9.png)
![image](https://user-images.githubusercontent.com/45677685/121518129-b63bc000-ca22-11eb-8676-be3487365065.png)
还是这样  不知道什么问题

**Comment by Hermit10** [comment]
已经更新，再试试0620版本
