### ISSUE TITLE
Soft Link 模式无法创建链接

### ISSUE THREAD

**Issue by sarieri** [Hermit10/temp#7]
Ojz，好像软链模式有点问题。

Create log file: Log/2021-06-12-22-39-53.txt

[*]======================================AVDC======================================
[*]                           Current Version: 20210611                            
[*]                    基于项目 https://github.com/moyy996/AVDC 修改                     
[*]================================================================================
[+]Find 173 movies
[!] --- Soft link mode is ENABLE! ----
[!]Round (1) - 0.57% - [1/173]
[!]Making Data for   [X:Mako Oda Megapack/ADN-061.mp4], the number is [ADN-061]
[+] ---Debug info---
   [+]-actor        : 織田真子
   [+]-cover        : https://javbus.com/pics/cover/4r55_b.jpg
   [+]-director     : はんきゅう太郎
   [+]-imagecut     : 1
   [+]-number       : ADN-061
   [+]-outline      : 亡き父の遺した居酒屋で元気に働くみゆきは、跡を継いで店主となった義兄と二人で店を切り盛りしていた。ある日、経営不振の影響で、店への銀行融資が止まる事を知ったみゆきは、銀行の顧問弁護士・一条寺のもとを訪ねるが…。
   [+]-publisher    : 大人のドラマ
   [+]-release      : 2015-05-03
   [+]-runtime      : 120
   [+]-source       : javbus.com
   [+]-studio       : アタッカーズ
   [+]-tag          : 巨乳, 單體作品, DMM獨家, 高畫質, 戲劇, 多選提交
   [+]-title        : 居酒屋哀歌-織田真子
   [+]-website      : https://www.javbus.com/ADN-061
   [+]-year         : 2015
   [+]-naming_media : number title
   [+]-naming_file  : number
   [+]-folder_name  : actor/number actor
[+] ---Debug info---
[+]Folder : X:/JAV_output/織田真子/ADN-061 織田真子
[+]From   : javbus.com
[+]Thumb Existed!     ADN-061-thumb.jpg
[+]Poster Existed!    ADN-061-poster.jpg
[-]Error in pasteFileToFolder: [WinError 4390] 此文件或目录不是一个重分析点。: 'X:Mako Oda Megapack/ADN-061.mp4' -> 'X:/JAV_output/織田真子/ADN-061 織田真子/ADN-061.mp4'
[+]Nfo Existed!       ADN-061.nfo
[*]================================================================================

**Comment by Hermit10** [comment]
对软连接不熟。改天研究下。

**Comment by Hermit10** [comment]
X盘是本地硬盘吗？软链接源文件可以在任意盘，但生成的软链接目标文件只能保存本地磁盘。

**Comment by Hermit10** [comment]
更新2021.07.11试试。
目前可以把软链接指向网络硬盘或本地硬盘。但是保存软链接的符号文件必须是本地硬盘。
