### ISSUE TITLE
javdb还是不能搜刮

### ISSUE THREAD

**Issue by cboxaddd** [Hermit10/temp#8]
<img width="512" alt="1" src="https://user-images.githubusercontent.com/86119449/122584876-73669180-d08d-11eb-9c64-b17f43b8c4ef.png">
<img width="512" alt="2" src="https://user-images.githubusercontent.com/86119449/122584989-9002c980-d08d-11eb-8396-fbf70bbe7a62.png">

**Comment by Hermit10** [comment]
好，晚点我看下原因。

**Comment by Hermit10** [comment]
这有点奇怪，我这边刮削正常。
![image](https://user-images.githubusercontent.com/24836174/122633083-42c43d80-d109-11eb-9a99-7ac3764f279a.png)
![image](https://user-images.githubusercontent.com/24836174/122633084-448e0100-d109-11eb-9b21-a4b0dace6e7e.png)

**Comment by cboxaddd** [comment]
可以加个联系方式么，我觉得是不是我的环境跟您的不一样

**Comment by cboxaddd** [comment]
会不会是不能有中文路径
<img width="512" alt="3" src="https://user-images.githubusercontent.com/86119449/122633355-c9c5e580-d10a-11eb-8782-0b20347436a0.png">

**Comment by Hermit10** [comment]
telgrame @hermit10

**Comment by Hermit10** [comment]
Fc2 PPV 1864290.mp4
这个番号识别问题已经改了
![image](https://user-images.githubusercontent.com/24836174/122633906-9afd3e80-d10d-11eb-9bcf-de0a21520ce0.png)

**Comment by cboxaddd** [comment]
电报加您了，老哥

**Comment by Hermit10** [comment]
已修改，更新最新版本吧。
