### ISSUE TITLE
Error in AVDC_Main.coreMain5: _ssl.c:1112: The handshake operation timed out

### ISSUE THREAD

**Issue by sirliu** [Hermit10/temp#9]
如题，出现这个错误，换一个代理工具则出现
`Error in AVDC_Main.coreMain5: EOF occurred in violation of protocol (_ssl.c:1129)`

**Comment by Hermit10** [comment]
可能Google翻译请求太多了被封了，把翻译改成日语

**Comment by Hermit10** [comment]
已改成有道翻译

**Comment by sirliu** [comment]
不如加一个开关

**Comment by Hermit10** [comment]
可以考虑。不过Google翻译容易被封，质量也差些，付费api质量会好些。
